FROM rockylinux:9

RUN dnf update -y

RUN dnf install -y dnf install wget rsync cmake openssl openssl-devel p7zip

RUN dnf install epel-release -y
RUN dnf group install -y "Development Tools"
RUN dnf install -y findutils gcc-gfortran gnupg2 hostname iproute python3 python3-pip python3-setuptools unzip python3-boto3

RUN dnf config-manager --set-enabled devel
RUN dnf update -y
RUN dnf install -y yum-utils
RUN yum install -y redhat-lsb-core

RUN yum install -y bzip2
RUN yum install -y gzip
RUN yum install -y which

#git clone https://gitlab.jsc.fz-juelich.de/deep-sea/wp3/software/spack.git
#git clone https://gitlab.jsc.fz-juelich.de/deep-sea/wp3/software/spack.git

# mkdir /home/di93nad
# mv /bdpo-pmpi-wrapper-4.2.1.tar.gz /home/di93nad/
# ls /home/di93nad/
