FROM amd64/ubuntu:jammy

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y
RUN apt install -y apt-utils
RUN apt install -y build-essential ca-certificates coreutils curl environment-modules gfortran git gpg lsb-release python3 python3-distutils python3-venv unzip zip python3-dev
RUN apt install -y git
RUN apt install -y gcc
RUN apt install -y bzip2 curl file gcc gfortran git gnupg2 gzip
RUN apt install -y make patch unzip python3 python3-dev tree
#RUN apt install -y bison-devel
#RUN apt install -y bison-dev
#RUN apt install -y bison
RUN apt install -y patchelf
RUN apt install -y libffi8
RUN apt install -y libffindex0-dev
RUN apt install -y libjson-glib-dev
#mkdir /home/di93nad
#mv /bdpo-pmpi-wrapper-4.2.1.tar.gz /home/di93nad/
#ls /home/di93nad/
